name: emscripten 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: mymindstorm/setup-emsdk@v11
      - run: git submodule update --init --recursive
      
      - name: Lua build
        run: wget https://www.lua.org/ftp/lua-5.4.3.tar.gz && tar -zxvf lua-5.4.3.tar.gz && cd lua-5.4.3 && make generic CC="emcc -s WASM=1" && cd src && mv liblua.a ../../ && cd ../../
      
      - name: sinen build
        run: cd external/sinen && emcmake cmake -B build && cd build && make -j2 && cd ../../../
      - name: CMake
        run: emcmake cmake .
      - name: Build
        run: make -j2