name: Emscripten(Web) 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: mymindstorm/setup-emsdk@v11
      - run: git submodule update --init --recursive
      
      - name: CMake
        run: emcmake cmake -B build
      - name: Build
        run: |
          cp -r data build
          cp shell_minimum.html build
          cp pre.js build
          cd build && make -j2
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages
          folder: build
          ssh-key: ${{ secrets.DEPLOY_KEY }}